var data=[
			{
				path:'data/0',
				name:'微云',
				child:[
						{	
							path:'data/0/child/0',
							name:'js课程',
							child:[
									{
										path:'data/0/child/0/child/0',
										name:'123',
										child:[]
									},
									{
										path:'data/0/child/0/child/1',
										name:'113',
										child:[
												{
													path:'data/0/child/0/child/1/child/0',
													name:'111',
													child:[]
												},
												{
													path:'data/0/child/0/child/1/child/1',
													name:'112',
													child:[]
												}
										
											]
									},
									{
										path:'data/0/child/0/child/2',
										name:'323',
										child:[]
									},
									{
										path:'data/0/child/0/child/3',
										name:'333',
										child:[]
									}
							
								]
						},
						{	
							path:'data/0/child/1',
							name:'css课程',
							child:[
									{
										path:'data/0/child/1/child/0',
										name:'223',
										child:[]
									},
									{
										path:'data/0/child/1/child/1',
										name:'224',
										child:[
												{
													path:'data/0/child/1/child/1/child/0',
													name:'211',
													child:[]
												},
												{
													path:'data/0/child/1/child/1/child/1',
													name:'212',
													child:[]
												}
										
											]
									},
									{
										path:'data/0/child/1/child/2',
										name:'226',
										child:[]
									}
							
								]
						}
				
				]
			}
		];
